AWSTemplateFormatVersion: '2010-09-09'
Description: 'Homework Scraper Lambda Function with EventBridge Scheduler'

Parameters:
  ProjectName:
    Type: String
    Default: homework-scraper
    Description: Name of the project
  
  ScheduleExpression:
    Type: String
    Default: "cron(30 16 ? * SUN,MON,TUE,WED,THU,FRI *)"
    Description: EventBridge schedule expression - runs at 16:30 every day except Saturday
  
  SecretsManagerSecretName:
    Type: String
    Default: homework-scraper-credentials
    Description: Name of the Secrets Manager secret containing login credentials

Resources:
  # Secrets Manager Secret for login credentials
  LoginCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretsManagerSecretName
      Description: Login credentials for homework portal
      SecretString: !Sub |
        {
          "username": "REPLACE_WITH_ACTUAL_USERNAME",
          "password": "REPLACE_WITH_ACTUAL_PASSWORD"
        }

  # ECR Repository for Docker images
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ProjectName
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [{
              "rulePriority": 1,
              "selection": {
                "tagStatus": "untagged",
                "countType": "sinceImagePushed",
                "countUnit": "days",
                "countNumber": 7
              },
              "action": {
                "type": "expire"
              }
            }]
          }

  # DynamoDB Table for homework items
  HomeworkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: homework-items
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: date
          AttributeType: S
        - AttributeName: hour_subject
          AttributeType: S
      KeySchema:
        - AttributeName: date
          KeyType: HASH
        - AttributeName: hour_subject
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # IAM Role for Lambda function
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:DescribeTable
                  - dynamodb:CreateTable
                Resource: 
                  - !GetAtt HomeworkTable.Arn
                  - !Sub '${HomeworkTable.Arn}/index/*'
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref LoginCredentials

  # Lambda Function
  HomeworkScraperFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-function'
      Role: !GetAtt LambdaExecutionRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}:latest'
      Timeout: 900  # 15 minutes
      MemorySize: 2048
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref HomeworkTable
          SECRETS_MANAGER_SECRET_NAME: !Ref LoginCredentials
          LOGIN_URL: https://webtop.smartschool.co.il/account/login
          HOMEWORK_URL: https://webtop.smartschool.co.il/Student_Card/11
          AWS_REGION: !Ref AWS::Region
          NODE_ENV: production
          PLAYWRIGHT_HEADLESS: true

  # EventBridge Rule for scheduling
  ScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${ProjectName}-schedule'
      Description: 'Triggers homework scraper on schedule'
      ScheduleExpression: !Ref ScheduleExpression
      State: ENABLED
      Targets:
        - Arn: !GetAtt HomeworkScraperFunction.Arn
          Id: HomeworkScraperTarget
          Input: |
            {
              "source": "eventbridge.scheduler",
              "detail": {
                "scheduled": true,
                "timestamp": "{{ aws.events.event.ingestion-time }}"
              }
            }

  # Permission for EventBridge to invoke Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref HomeworkScraperFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduleRule.Arn

Outputs:
  ECRRepositoryURI:
    Description: URI of the ECR repository
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}'
    Export:
      Name: !Sub '${ProjectName}-ecr-uri'
  
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt HomeworkScraperFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-function-arn'
  
  DynamoDBTableName:
    Description: Name of the DynamoDB table
    Value: !Ref HomeworkTable
    Export:
      Name: !Sub '${ProjectName}-table-name'
  
  ScheduleRuleArn:
    Description: ARN of the EventBridge schedule rule
    Value: !GetAtt ScheduleRule.Arn
    Export:
      Name: !Sub '${ProjectName}-schedule-arn'